# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 444)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_image = QtWidgets.QLabel(self.centralwidget)
        self.lbl_image.setGeometry(QtCore.QRect(30, 30, 291, 161))
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setObjectName("lbl_image")
        self.btn_loadImage = QtWidgets.QPushButton(self.centralwidget)
        self.btn_loadImage.setGeometry(QtCore.QRect(110, 220, 75, 23))
        self.btn_loadImage.setObjectName("btn_loadImage")
        self.cbox_algorithm = QtWidgets.QComboBox(self.centralwidget)
        self.cbox_algorithm.setEnabled(False)
        self.cbox_algorithm.setGeometry(QtCore.QRect(420, 220, 211, 22))
        self.cbox_algorithm.setObjectName("cbox_algorithm")
        self.lbl_resultImg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_resultImg.setGeometry(QtCore.QRect(380, 30, 291, 161))
        self.lbl_resultImg.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_resultImg.setObjectName("lbl_resultImg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_image.setText(_translate("MainWindow", "image goes here"))
        self.btn_loadImage.setText(_translate("MainWindow", "Load Image"))
        self.lbl_resultImg.setText(_translate("MainWindow", "result image"))
